all:
	make all -C src

clean:
	make clean -C src
	
# управление приложением
app_all:
	make app_all -C src

app_clean:
	make app_clean -C src

# управление библиотекой libcmsis
cmsis_all:
	make cmsis_all -C src

cmsis_clean:
	make cmsis_clean -C src

# управление библиотекой libhardware
hardware_all:
	make hardware_all -C src

hardware_clean:
	make hardware_clean -C src
	
# управление библиотекой libethernet
ethernet_all:
	make ethernet_all -C src

ethernet_clean:
	make ethernet_clean -C src
	
# управление библиотекой libuip
uip_all:
	make uip_all -C src

uip_clean:
	make uip_clean -C src


# управление библиотекой libuip-1.0
uip-1.0_all:
	make uip-1.0_all -C src

uip-1.0_clean:
	make uip-1.0_clean -C src

uip-1.0_update_httpd_fsdata:
	make uip-1.0_update_httpd_fsdata -C src

# управление библиотекой libfreertos-6.0.2
freertos-6.0.2_all:
	make freertos-6.0.2_all -C src

freertos-6.0.2_clean:
	make freertos-6.0.2_clean -C src






	