SRC_DIR=./..

LIBNAME = libdiskio

include $(SRC_DIR)/rules.mk

CFLAGS += -I./							\
          -I$(SRC_DIR)/include			\
          -I$(STM32_CMSIS_DIR)			\
          -I$(STM32_PERIFERIAL_DRV_DIR)	\
          -I$(FATFS_DIR) 				\
          -DUSE_STDPERIPH_DRIVER




