SRC_DIR=./..

LIBNAME = libhardware

LIB_SRC_DIR=$(STM32_PERIFERIAL_DRV_DIR)

include $(SRC_DIR)/rules.mk

CFLAGS += -I./                   \
          -I$(SRC_DIR)/include   \
          -I$(STM32_CMSIS_DIR)  \
          $(HARDWARE_DEFS)





