SRC_DIR=./..

LIBNAME = libfreertos-6.0.2
FULLNAME = $(LIB_DIR)/$(LIBNAME).a

include $(SRC_DIR)/rules.mk

CFLAGS +=	-I./						\
			-I$(SRC_DIR)/include		\
			-I$(SRC_DIR)/libcmsis		\
			-I$(SRC_DIR)/libhardware
