SRC_DIR=./..

LIBNAME = libethernet
FULLNAME = $(LIB_DIR)/$(LIBNAME).a

include $(SRC_DIR)/rules.mk

CFLAGS += -I./                     \
          -I$(SRC_DIR)/libcmsis    \
          -I$(SRC_DIR)/libhardware




